// RIBAL products + Assessment + Contact — 9 entries total.
window.RIBAL_PRODUCTS = [
  {
    slug: 'his', code: 'RB-01', iconKey: 'his', color: '#3F5E5C',
    name:    { en: 'HIS', fr: 'HIS', ar: 'HIS' },
    sub:     { en: 'Hospital Information System', fr: 'Système d\'information hospitalier', ar: 'نظام معلومات المستشفى' },
    tagline: { en: 'The central brain of the hospital — from one site to a provincial cluster.',
               fr: 'Le cerveau central de l\'hôpital — d\'un site unique à un réseau régional.',
               ar: 'العقل المركزي للمستشفى — من موقع واحد إلى عناقيد محافظات.' },
    badge:   { big: '3–5k', lbl: { en: 'Bed cluster', fr: 'Réseau de lits', ar: 'حجم العنقود' } },
    chips:   [ { tone: 'mint', en: 'Product · 01', fr: 'Produit · 01', ar: 'منتج · ٠١' },
               { tone: 'good', en: 'City-scale proven', fr: 'Éprouvé à l\'échelle d\'une ville', ar: 'مُثبت على مستوى مدينة' } ],
    overview: { what: { en: 'Our flagship HIS unifies clinical and administrative workflows across EMR, ED, OPD, IPD, surgery, pharmacy, oral & dental, ERP and patient portal.',
                        fr: 'Notre HIS phare unifie les processus cliniques et administratifs : DPI, urgences, consultations externes, hospitalisation, chirurgie, pharmacie, soins bucco-dentaires, ERP et portail patient.',
                        ar: 'يوحّد نظام HIS سير العمل السريري والإداري عبر السجل الطبي، الطوارئ، العيادات، التنويم، الجراحة، الصيدلية، والبوابة.' },
                kpis: [ { v: '50+',   l: { en: 'Modules', fr: 'Modules', ar: 'وحدة' } },
                        { v: '38 yr', l: { en: 'Platform maturity', fr: 'Maturité de la plateforme', ar: 'نضج المنصّة' } },
                        { v: '3–5k',  l: { en: 'Bed cluster refs', fr: 'Références réseaux de lits', ar: 'مراجع عناقيد' } } ] },
    audience: { list: [
      { h: { en: 'Single hospitals',   fr: 'Hôpitaux individuels', ar: 'مستشفيات منفردة' }, p: { en: 'Replacing or modernizing the core HIS.', fr: 'Remplacement ou modernisation du HIS central.', ar: 'استبدال أو تحديث HIS الأساسي.' } },
      { h: { en: 'Specialty hospitals',fr: 'Hôpitaux spécialisés', ar: 'مستشفيات تخصّصية' }, p: { en: 'Dialysis, dental, oncology branches.', fr: 'Dialyse, dentaire, oncologie.', ar: 'غسيل كلى، أسنان، أورام.' } },
      { h: { en: 'Provincial clusters',fr: 'Réseaux régionaux', ar: 'عناقيد محافظات' }, p: { en: 'Multi-hospital networks on one shared HIS.', fr: 'Réseaux multi-hôpitaux sur un HIS unique partagé.', ar: 'شبكات مستشفيات على HIS واحد.' } },
      { h: { en: 'Government networks',fr: 'Réseaux publics', ar: 'شبكات حكومية' }, p: { en: 'MOH / NGHA / Seha standardization.', fr: 'Standardisation MOH / NGHA / Seha.', ar: 'الصحة والحرس الوطني وسعها.' } },
    ] },
    features: { list: [
      { h: { en: 'Single hospital to provincial cluster', fr: 'De l\'hôpital unique au réseau régional', ar: 'من مستشفى إلى عنقود محافظات' },
        p: { en: 'Same codebase across deployment sizes.', fr: 'Une seule base de code, quelle que soit la taille du déploiement.', ar: 'نفس الكود في كل أحجام النشر.' },
        sub: [ { en: 'Linear scale path', fr: 'Montée en charge linéaire', ar: 'مسار توسّع خطي' }, { en: 'Multi-tenant governance', fr: 'Gouvernance multi-tenant', ar: 'حوكمة متعدّدة الجهات' }, { en: 'Identical UI / workflows', fr: 'Interface et processus identiques', ar: 'نفس الواجهة وسير العمل' } ] },
      { h: { en: 'Modular & extensible', fr: 'Modulaire et extensible', ar: 'مرن وقابل للتوسعة' },
        p: { en: '50+ modules — adopt what you need.', fr: 'Plus de 50 modules — déployez uniquement ce dont vous avez besoin.', ar: 'أكثر من ٥٠ وحدة — تبنَّ ما تحتاج.' },
        sub: [ { en: 'EMR · ED · OPD · IPD', fr: 'DPI · Urgences · Externe · Hospi', ar: 'السجل · الطوارئ · العيادات · التنويم' }, { en: 'Patient portal · mobile', fr: 'Portail patient · mobile', ar: 'بوّابة المرضى · الجوّال' }, { en: 'BI · ERP', fr: 'BI · ERP', ar: 'ذكاء الأعمال · ERP' } ] },
      { h: { en: 'Saudi-localized', fr: 'Adapté au marché saoudien', ar: 'محلي للمملكة' },
        p: { en: 'Co-developed for the Saudi market.', fr: 'Co-développé pour le marché saoudien.', ar: 'بتطوير مشترك للسوق السعودي.' },
        sub: [ { en: 'Arabic UI · Saudi ID', fr: 'Interface arabe · ID saoudien', ar: 'واجهة عربية · الهوية الوطنية' }, { en: 'NPHIES connectors', fr: 'Connecteurs NPHIES', ar: 'وصلات نفيس' }, { en: 'Hajj / Umrah flows', fr: 'Parcours Hajj / Umrah', ar: 'مسارات الحج والعمرة' } ] },
    ] },
    proof: { summary: { en: 'Deployed across hundreds of Turkish hospitals — including provincial clusters in the 3,000–5,000-bed range.',
                        fr: 'Déployé dans des centaines d\'hôpitaux turcs — y compris des réseaux régionaux de 3 000 à 5 000 lits.',
                        ar: 'نُشر في مئات المستشفيات التركية — بما فيها عناقيد محافظات بأسرّة ٣–٥ آلاف.' },
             stats: [ { v: '650+', l: { en: 'Deployments worldwide', fr: 'Déploiements dans le monde', ar: 'نشر عالميًا' } },
                      { v: '300+', l: { en: 'In Turkey alone', fr: 'Rien qu\'en Turquie', ar: 'في تركيا' } },
                      { v: 'City-scale', l: { en: 'Full-city deployments', fr: 'Déploiements à l\'échelle d\'une ville', ar: 'مستوى مدينة' } } ] },
    phases: [
      { step: 1, when: { en: 'Weeks 1–6', fr: 'Semaines 1 à 6', ar: 'الأسابيع ١-٦' }, h: { en: 'Discovery & migration plan', fr: 'Cadrage et plan de migration', ar: 'الاستكشاف والانتقال' }, p: { en: 'Audit, gap analysis, migration design.', fr: 'Audit, analyse des écarts, conception de la migration.', ar: 'تدقيق، تحليل الفجوات، تصميم انتقال.' }, deliv: { en: 'Migration plan', fr: 'Plan de migration', ar: 'خطة الانتقال' } },
      { step: 2, when: { en: 'Weeks 7–20', fr: 'Semaines 7 à 20', ar: 'الأسابيع ٧-٢٠' }, h: { en: 'Configuration & pilot', fr: 'Paramétrage et pilote', ar: 'التهيئة والتجربة' }, p: { en: 'Modules configured, two-ward pilot.', fr: 'Modules paramétrés, pilote sur deux services.', ar: 'تهيئة الوحدات، تجربة جناحَين.' }, deliv: { en: 'Pilot go-live', fr: 'Mise en production du pilote', ar: 'تشغيل التجربة' } },
      { step: 3, when: { en: 'Weeks 21–36', fr: 'Semaines 21 à 36', ar: 'الأسابيع ٢١-٣٦' }, h: { en: 'Rollout', fr: 'Déploiement global', ar: 'التوسعة' }, p: { en: 'Full hospital live, optimization.', fr: 'Mise en production totale, optimisation.', ar: 'تشغيل المستشفى، تحسين.' }, deliv: { en: 'Production live', fr: 'Production en service', ar: 'الإنتاج' } },
    ],
    performance: { metrics: [
      { v: '~30%',    t: 'up',   l: { en: 'Doc time saved', fr: 'Temps de saisie économisé', ar: 'وفر التوثيق' } },
      { v: '~99.95%', t: 'flat', l: { en: 'Uptime SLA', fr: 'Disponibilité (SLA)', ar: 'جاهزية الإنتاج' } },
      { v: '38 yr',   t: 'flat', l: { en: 'Platform maturity', fr: 'Maturité de la plateforme', ar: 'نضج المنصّة' } },
      { v: '3–5k',    t: 'up',   l: { en: 'Bed cluster refs', fr: 'Références réseaux de lits', ar: 'مراجع عناقيد' } },
    ], bars: [
      { l: { en: 'EMR completeness', fr: 'Couverture du DPI', ar: 'اكتمال السجل' }, pct: 95 },
      { l: { en: 'NPHIES readiness', fr: 'Compatibilité NPHIES', ar: 'جاهزية نفيس' }, pct: 92 },
      { l: { en: 'Arabic / RTL',     fr: 'Arabe / sens RTL', ar: 'دعم العربية' }, pct: 100 },
      { l: { en: 'Mobile coverage',  fr: 'Couverture mobile', ar: 'الجوّال' },     pct: 88 },
    ] },
  },
  {
    slug: 'pacs', code: 'RB-02', iconKey: 'pacs', color: '#406582',
    name:    { en: 'PACS', fr: 'PACS', ar: 'PACS' },
    sub:     { en: 'Picture Archiving & Communication', fr: 'Archivage et diffusion d\'imagerie', ar: 'أرشفة وتبادل الصور' },
    tagline: { en: 'Unified medical imaging — one hospital or a whole network.',
               fr: 'Imagerie médicale unifiée — d\'un hôpital à un réseau entier.',
               ar: 'أرشفة موحّدة — لمستشفى أو شبكة كاملة.' },
    badge:   { big: '650+', lbl: { en: 'Imaging sites', fr: 'Sites d\'imagerie', ar: 'مواقع تصوير' } },
    chips:   [ { tone: 'mint', en: 'Product · 02', fr: 'Produit · 02', ar: 'منتج · ٠٢' }, { tone: 'info', en: 'NPHIES-ready', fr: 'Compatible NPHIES', ar: 'جاهز لنفيس' } ],
    overview: { what: { en: 'Picture Archiving and Communication System — runs as a single-hospital PACS or a centralized archive. Filmless, instant retrieval.',
                        fr: 'Système d\'archivage et de diffusion d\'imagerie — fonctionne en PACS d\'hôpital unique ou en archive centralisée. Sans film, accès instantané.',
                        ar: 'نظام أرشفة وتبادل الصور — لمستشفى واحد أو أرشيف مركزي. بدون أفلام، استرجاع فوري.' },
                kpis: [ { v: '90s',     l: { en: 'Avg retrieval', fr: 'Temps moyen d\'accès', ar: 'متوسط الاسترجاع' } },
                        { v: 'Filmless',l: { en: 'Replaces film', fr: 'Remplace le film', ar: 'بدل الأفلام' } },
                        { v: 'IHE/HL7', l: { en: 'Standards', fr: 'Normes', ar: 'المعايير' } } ] },
    audience: { list: [
      { h: { en: 'Single hospitals',     fr: 'Hôpitaux individuels', ar: 'مستشفيات منفردة' }, p: { en: 'Modernizing the imaging stack.', fr: 'Modernisation de l\'environnement d\'imagerie.', ar: 'تحديث منظومة التصوير.' } },
      { h: { en: 'Multi-site networks',  fr: 'Réseaux multi-sites', ar: 'شبكات متعددة' }, p: { en: 'Eliminating imaging fragmentation.', fr: 'Fin de la fragmentation de l\'imagerie.', ar: 'إزالة التشتّت.' } },
      { h: { en: 'Radiology chains',     fr: 'Chaînes de radiologie', ar: 'سلاسل أشعة' }, p: { en: 'Standalone radiology centers.', fr: 'Centres de radiologie indépendants.', ar: 'مراكز أشعة مستقلة.' } },
      { h: { en: 'Government networks',  fr: 'Réseaux publics', ar: 'شبكات حكومية' }, p: { en: 'Regional / national imaging programs.', fr: 'Programmes d\'imagerie régionaux ou nationaux.', ar: 'برامج تصوير إقليمية ووطنية.' } },
    ] },
    features: { list: [
      { h: { en: 'Single-site or centralized', fr: 'Mono-site ou centralisé', ar: 'منفرد أو مركزي' },
        p: { en: 'Same product, two deployment modes.', fr: 'Un même produit, deux modes de déploiement.', ar: 'منتج واحد بنمطَي نشر.' },
        sub: [ { en: 'CT · MRI · X-Ray · PET', fr: 'Scanner · IRM · Radio · PET', ar: 'مقطعية · رنين · سينية · PET' }, { en: 'Mammo · US', fr: 'Mammo · Échographie', ar: 'الثدي · الموجات' }, { en: 'DICOM integration', fr: 'Intégration DICOM', ar: 'تكامل DICOM' } ] },
      { h: { en: 'AI-assisted reading', fr: 'Lecture assistée par IA', ar: 'قراءة بالذكاء' },
        p: { en: 'Optional X-Eye modules in the worklist.', fr: 'Modules X-Eye optionnels directement dans la worklist.', ar: 'وحدات X-Eye اختيارية في قائمة العمل.' },
        sub: [ { en: 'Mammo · Toraks · RibOut', fr: 'Sein · Thorax · Côtes', ar: 'الثدي · الصدر · الأضلاع' }, { en: 'Worklist-embedded', fr: 'Intégré à la worklist', ar: 'مضمّن بقائمة العمل' }, { en: 'Audit logs', fr: 'Journaux d\'audit', ar: 'سجلات تدقيق' } ] },
      { h: { en: 'Radiologist productivity', fr: 'Productivité du radiologue', ar: 'إنتاجية الطبيب' },
        p: { en: 'Worklists, reporting templates, routing.', fr: 'Worklists, modèles de comptes-rendus, routage.', ar: 'قوائم عمل وقوالب ومسارات.' },
        sub: [ { en: 'Routing per shift', fr: 'Routage par garde', ar: 'توجيه حسب الورديات' }, { en: 'Macros & templates', fr: 'Macros et modèles', ar: 'قوالب وماكرو' }, { en: 'KPI dashboards', fr: 'Tableaux de bord KPI', ar: 'لوحات مؤشرات' } ] },
    ] },
    proof: { summary: { en: 'Deployed at single hospitals and across multi-hospital networks. National-scale references in Central Asia.',
                        fr: 'Déployé dans des hôpitaux uniques comme dans des réseaux multi-hôpitaux. Références à l\'échelle nationale en Asie centrale.',
                        ar: 'نُشر في مستشفيات منفردة وشبكات. مراجع وطنية في آسيا الوسطى.' },
             stats: [ { v: 'Single+', l: { en: 'Both modes', fr: 'Les deux modes', ar: 'كلا النمطَين' } },
                      { v: 'Filmless',l: { en: 'Film replaced', fr: 'Film remplacé', ar: 'استبدال الأفلام' } },
                      { v: '24/7',    l: { en: 'Saudi support', fr: 'Support local en Arabie', ar: 'دعم بالمملكة' } } ] },
    phases: [
      { step: 1, when: { en: 'Weeks 1–4', fr: 'Semaines 1 à 4', ar: 'الأسابيع ١-٤' }, h: { en: 'Discovery', fr: 'Cadrage', ar: 'الاستكشاف' }, p: { en: 'Site survey, modality inventory.', fr: 'Étude du site, inventaire des modalités.', ar: 'مسح ميداني، جرد الأجهزة.' }, deliv: { en: 'Solution design', fr: 'Conception de la solution', ar: 'تصميم الحل' } },
      { step: 2, when: { en: 'Weeks 5–16', fr: 'Semaines 5 à 16', ar: 'الأسابيع ٥-١٦' }, h: { en: 'Build & pilot', fr: 'Construction et pilote', ar: 'البناء والتجربة' }, p: { en: 'Deploy, integrate, train.', fr: 'Déploiement, intégration, formation.', ar: 'نشر، تكامل، تدريب.' }, deliv: { en: 'Pilot go-live', fr: 'Mise en production du pilote', ar: 'تشغيل التجربة' } },
      { step: 3, when: { en: 'Weeks 17–26', fr: 'Semaines 17 à 26', ar: 'الأسابيع ١٧-٢٦' }, h: { en: 'Rollout', fr: 'Déploiement global', ar: 'التوسعة' }, p: { en: 'Remaining sites, routing tuning.', fr: 'Sites restants, ajustement du routage.', ar: 'المواقع المتبقية، ضبط المسارات.' }, deliv: { en: 'Production live', fr: 'Production en service', ar: 'الإنتاج' } },
    ],
    performance: { metrics: [
      { v: '~90s',  t: 'down', l: { en: 'Retrieval time', fr: 'Temps de récupération', ar: 'زمن الاسترجاع' } },
      { v: '+17%',  t: 'up',   l: { en: 'Early-detection lift', fr: 'Gain de détection précoce', ar: 'تحسّن الكشف' } },
      { v: '~25%',  t: 'down', l: { en: 'Repeat scan reduction', fr: 'Examens répétés en moins', ar: 'تقليل الفحوصات المكرّرة' } },
      { v: '0',     t: 'flat', l: { en: 'Film cost', fr: 'Coût du film', ar: 'تكلفة الأفلام' } },
    ], bars: [
      { l: { en: 'Modality coverage',  fr: 'Couverture des modalités', ar: 'تغطية الأجهزة' }, pct: 96 },
      { l: { en: 'Radiologist adoption',fr: 'Adoption par les radiologues', ar: 'تبنّي الأطباء' }, pct: 89 },
      { l: { en: 'Cross-site routing', fr: 'Routage inter-sites', ar: 'التوجيه' },     pct: 82 },
      { l: { en: 'AI module coverage', fr: 'Couverture des modules IA', ar: 'تغطية الذكاء' }, pct: 70 },
    ] },
  },
  {
    slug: 'icu', code: 'RB-03', iconKey: 'icu', color: '#8E6566',
    name:    { en: 'ICU iVital', fr: 'ICU iVital', ar: 'iVital' },
    sub:     { en: 'Critical-care monitoring with predictive AI', fr: 'Surveillance des soins critiques avec IA prédictive', ar: 'رصد العناية المركّزة بذكاء تنبؤي' },
    tagline: { en: 'Spots early warning signs and alerts staff.', fr: 'Détecte les signes précoces et alerte les équipes.', ar: 'يكتشف علامات الإنذار المبكر.' },
    badge:   { big: '~30%', lbl: { en: 'Op-cost saved', fr: 'Coûts d\'exploitation économisés', ar: 'وفر تشغيلي' } },
    chips:   [ { tone: 'mint', en: 'Product · 03', fr: 'Produit · 03', ar: 'منتج · ٠٣' }, { tone: 'good', en: 'Predictive AI', fr: 'IA prédictive', ar: 'ذكاء تنبؤي' } ],
    overview: { what: { en: 'iVital automates ICU operations. Vitals, labs, ventilators and monitors feed one system with AI alerts.',
                        fr: 'iVital automatise le fonctionnement des soins intensifs. Constantes, analyses, ventilateurs et moniteurs alimentent un système unique avec alertes IA.',
                        ar: 'تُؤتمت iVital العناية المركّزة. تتدفّق العلامات والمختبرات والأجهزة لنظام واحد.' },
                kpis: [ { v: '100%', l: { en: 'Digital nursing', fr: 'Soins infirmiers 100 % numériques', ar: 'تمريض رقمي' } },
                        { v: '~30%', l: { en: 'Op-cost reduction', fr: 'Réduction des coûts d\'exploitation', ar: 'وفر تشغيلي' } },
                        { v: 'AI',   l: { en: 'Predictive', fr: 'Prédictif', ar: 'تنبؤي' } } ] },
    audience: { list: [
      { h: { en: 'Single hospitals',  fr: 'Hôpitaux individuels', ar: 'مستشفيات منفردة' }, p: { en: 'Replacing paper ICU charts.', fr: 'Remplacement des dossiers de réanimation papier.', ar: 'استبدال الرصد الورقي.' } },
      { h: { en: 'Multi-ICU networks',fr: 'Réseaux de plusieurs unités', ar: 'شبكات وحدات' }, p: { en: 'Standardizing protocols across ICUs.', fr: 'Standardisation des protocoles entre unités.', ar: 'توحيد البروتوكولات.' } },
      { h: { en: 'Rural facilities',  fr: 'Établissements ruraux', ar: 'منشآت ريفية' }, p: { en: 'Remote intensivist oversight.', fr: 'Supervision à distance par des réanimateurs.', ar: 'إشراف عن بُعد.' } },
      { h: { en: 'Gov health systems',fr: 'Systèmes publics de santé', ar: 'أنظمة حكومية' }, p: { en: 'Regional ICU command.', fr: 'Pilotage régional des soins intensifs.', ar: 'قيادة عناية إقليمية.' } },
    ] },
    features: { list: [
      { h: { en: 'Earlier deterioration detection', fr: 'Détection plus précoce des aggravations', ar: 'كشف أبكر للتدهور' }, p: { en: 'AI flags sepsis, respiratory failure ahead of manual.', fr: 'L\'IA signale sepsis et défaillances respiratoires avant la détection manuelle.', ar: 'الذكاء يُشعر بالخطر مبكرًا.' },
        sub: [ { en: 'Sepsis-3 scoring', fr: 'Score Sepsis-3', ar: 'مقاييس التعفّن' }, { en: 'Trend analysis', fr: 'Analyse des tendances', ar: 'تحليل الاتجاهات' }, { en: 'Configurable thresholds', fr: 'Seuils configurables', ar: 'حدود قابلة للتعديل' } ] },
      { h: { en: 'Centralized oversight', fr: 'Supervision centralisée', ar: 'إشراف مركزي' }, p: { en: 'Command center supervises multiple ICUs remotely.', fr: 'Un centre de pilotage supervise plusieurs unités à distance.', ar: 'غرفة قيادة تشرف على عدّة وحدات.' },
        sub: [ { en: 'Multi-site dashboard', fr: 'Tableau de bord multi-sites', ar: 'لوحة متعدّدة' }, { en: 'Video consult', fr: 'Consultation vidéo', ar: 'استشارة مرئية' }, { en: 'Tele-ICU compliant', fr: 'Conforme télé-réanimation', ar: 'متوافق Tele-ICU' } ] },
      { h: { en: 'Fully digital', fr: 'Tout numérique', ar: 'رقمي بالكامل' }, p: { en: 'Replaces paper charts, automates documentation.', fr: 'Remplace les dossiers papier, automatise la documentation.', ar: 'يستبدل الورق ويُؤتمت التوثيق.' },
        sub: [ { en: 'Auto-charting', fr: 'Saisie automatique', ar: 'تسجيل تلقائي' }, { en: 'Standard protocols', fr: 'Protocoles standardisés', ar: 'بروتوكولات موحّدة' }, { en: 'More care time', fr: 'Plus de temps pour les soins', ar: 'وقت أكثر للرعاية' } ] },
    ] },
    proof: { summary: { en: 'Deployed in Turkey and international implementations. ~20% Y1 op-cost cut, up to ~30% subsequent years.',
                        fr: 'Déployé en Turquie et dans plusieurs pays. Environ 20 % de réduction des coûts la première année, jusqu\'à 30 % les années suivantes.',
                        ar: 'نُشر في تركيا وتطبيقات دولية. ~٢٠٪ السنة الأولى، حتى ~٣٠٪ لاحقًا.' },
             stats: [ { v: '~20%', l: { en: 'Y1 op-cost cut', fr: 'Réduction de coûts an 1', ar: 'وفر السنة الأولى' } },
                      { v: '~30%', l: { en: 'Subsequent years', fr: 'Années suivantes', ar: 'السنوات اللاحقة' } },
                      { v: 'Hours',l: { en: 'Earlier deterioration alert', fr: 'Alerte de dégradation anticipée', ar: 'تنبيه أبكر' } } ] },
    phases: [
      { step: 1, when: { en: 'Weeks 1–4', fr: 'Semaines 1 à 4', ar: 'الأسابيع ١-٤' }, h: { en: 'Discovery', fr: 'Cadrage', ar: 'الاستكشاف' }, p: { en: 'Device inventory, alarm design.', fr: 'Inventaire des équipements, conception des alarmes.', ar: 'جرد الأجهزة، تصميم التنبيهات.' }, deliv: { en: 'Solution design', fr: 'Conception de la solution', ar: 'تصميم الحل' } },
      { step: 2, when: { en: 'Weeks 5–14', fr: 'Semaines 5 à 14', ar: 'الأسابيع ٥-١٤' }, h: { en: 'Build & pilot', fr: 'Construction et pilote', ar: 'البناء والتجربة' }, p: { en: 'Deploy, integrate devices, train.', fr: 'Déploiement, intégration des dispositifs, formation.', ar: 'نشر، تكامل، تدريب.' }, deliv: { en: 'Pilot go-live', fr: 'Mise en production du pilote', ar: 'تشغيل التجربة' } },
      { step: 3, when: { en: 'Weeks 15–24', fr: 'Semaines 15 à 24', ar: 'الأسابيع ١٥-٢٤' }, h: { en: 'Rollout', fr: 'Déploiement global', ar: 'التوسعة' }, p: { en: 'Remaining ICUs, command center.', fr: 'Unités restantes, centre de pilotage.', ar: 'الوحدات المتبقية، غرفة القيادة.' }, deliv: { en: 'Production live', fr: 'Production en service', ar: 'الإنتاج' } },
    ],
    performance: { metrics: [
      { v: '~20–30%', t: 'down', l: { en: 'ICU op-cost', fr: 'Coûts d\'exploitation soins intensifs', ar: 'تكلفة العناية' } },
      { v: '~4 hr',   t: 'down', l: { en: 'Earlier sepsis flag', fr: 'Détection sepsis plus précoce', ar: 'إشارة تعفّن أبكر' } },
      { v: '100%',    t: 'up',   l: { en: 'Paperless', fr: 'Sans papier', ar: 'بدون ورق' } },
      { v: '~35%',    t: 'down', l: { en: 'Documentation time', fr: 'Temps de documentation', ar: 'زمن التوثيق' } },
    ], bars: [
      { l: { en: 'Device coverage',  fr: 'Couverture des dispositifs', ar: 'تغطية الأجهزة' }, pct: 94 },
      { l: { en: 'Alert accuracy',   fr: 'Précision des alertes', ar: 'دقة التنبيهات' }, pct: 86 },
      { l: { en: 'Nurse adoption',   fr: 'Adoption par le personnel soignant', ar: 'تبنّي التمريض' }, pct: 91 },
      { l: { en: 'Protocol coverage',fr: 'Couverture des protocoles', ar: 'تغطية البروتوكولات' }, pct: 88 },
    ] },
  },
  {
    slug: 'lis', code: 'RB-04', iconKey: 'lis', color: '#5A6E8A',
    name:    { en: 'LIS', fr: 'LIS', ar: 'LIS' },
    sub:     { en: 'Laboratory Information System', fr: 'Système d\'information de laboratoire', ar: 'نظام معلومات المختبرات' },
    tagline: { en: 'Unified lab ordering, sample tracking and reporting.', fr: 'Prescription, suivi des échantillons et comptes-rendus de laboratoire unifiés.', ar: 'طلب فحوصات وتتبّع وتقارير موحّدة.' },
    badge:   { big: '~25%', lbl: { en: 'Repeat tests cut', fr: 'Tests répétés en moins', ar: 'تقليل التكرار' } },
    chips:   [ { tone: 'mint', en: 'Product · 04', fr: 'Produit · 04', ar: 'منتج · ٠٤' }, { tone: 'info', en: 'NPHIES-ready', fr: 'Compatible NPHIES', ar: 'جاهز لنفيس' } ],
    overview: { what: { en: 'Our LIS handles pre/analytical/post-analytical processes. Standalone or centralized.',
                        fr: 'Notre LIS couvre les phases pré-analytique, analytique et post-analytique. En autonome ou en mode centralisé.',
                        ar: 'يتولّى المراحل قبل التحليلية والتحليلية وبعد التحليلية. منفرد أو مركزي.' },
                kpis: [ { v: 'IHE',     l: { en: 'PCD · LAB · ITI', fr: 'PCD · LAB · ITI', ar: 'PCD · LAB · ITI' } },
                        { v: 'HL7',     l: { en: 'HIS-integrated', fr: 'Intégré au HIS', ar: 'متكامل HIS' } },
                        { v: 'Real-time',l: { en: 'Surveillance', fr: 'Surveillance', ar: 'رصد لحظي' } } ] },
    audience: { list: [
      { h: { en: 'Single hospitals',    fr: 'Hôpitaux individuels', ar: 'مستشفيات منفردة' }, p: { en: 'Upgrading the hospital lab.', fr: 'Modernisation du laboratoire hospitalier.', ar: 'تطوير مختبر المستشفى.' } },
      { h: { en: 'Multi-site lab chains',fr: 'Chaînes de laboratoires multi-sites', ar: 'سلاسل مختبرات' }, p: { en: 'Quality across cities.', fr: 'Qualité homogène entre les villes.', ar: 'جودة بين المدن.' } },
      { h: { en: 'Regional programs',   fr: 'Programmes régionaux', ar: 'برامج إقليمية' }, p: { en: 'Gov-run lab networks.', fr: 'Réseaux de laboratoires publics.', ar: 'شبكات مختبر حكومية.' } },
      { h: { en: 'Rural access',        fr: 'Accès en zone rurale', ar: 'وصول ريفي' }, p: { en: 'Rural sites lacking specialists.', fr: 'Sites ruraux sans spécialistes sur place.', ar: 'مواقع ريفية بدون أخصائيين.' } },
    ] },
    features: { list: [
      { h: { en: 'Standardized quality', fr: 'Qualité standardisée', ar: 'جودة موحّدة' }, p: { en: 'Unified protocols, cross-site QC.', fr: 'Protocoles unifiés, contrôle qualité inter-sites.', ar: 'بروتوكولات موحّدة، ضبط بين المواقع.' },
        sub: [ { en: 'Lot tracking', fr: 'Traçabilité des lots', ar: 'تتبّع الدفعات' }, { en: 'QC charts',  fr: 'Cartes de contrôle qualité', ar: 'مخططات ضبط جودة' }, { en: 'Cross-site QC', fr: 'CQ inter-sites', ar: 'ضبط بين المواقع' } ] },
      { h: { en: 'Fewer repeat tests', fr: 'Moins de tests redondants', ar: 'تكرار أقل' }, p: { en: 'Patient history follows them across the network.', fr: 'Le dossier du patient suit dans tout le réseau.', ar: 'تاريخ المريض عبر الشبكة.' },
        sub: [ { en: 'Network-wide history', fr: 'Historique sur tout le réseau', ar: 'تاريخ عبر الشبكة' }, { en: 'Order de-dup',  fr: 'Dédoublonnage des prescriptions', ar: 'إزالة التكرار' }, { en: 'Result reuse', fr: 'Réutilisation des résultats', ar: 'إعادة استخدام النتائج' } ] },
      { h: { en: 'Surveillance-ready', fr: 'Prêt pour la veille sanitaire', ar: 'جاهز لرصد الصحة' }, p: { en: 'Outbreak detection, screening, MoH reporting.', fr: 'Détection d\'épidémies, dépistage, déclarations ministérielles.', ar: 'كشف أوبئة، مسح، تقارير الصحة.' },
        sub: [ { en: 'Real-time signals', fr: 'Signaux en temps réel', ar: 'إشارات لحظية' }, { en: 'Screening cohorts', fr: 'Cohortes de dépistage', ar: 'مجموعات مسح' }, { en: 'MoH / SDAIA hooks', fr: 'Connecteurs MoH / SDAIA', ar: 'وصلات الصحة وسدايا' } ] },
    ] },
    proof: { summary: { en: 'Deployed inside single hospitals and across multi-region networks. IHE / HL7 compliant.', fr: 'Déployé dans des hôpitaux uniques comme dans des réseaux multi-régions. Conforme IHE / HL7.', ar: 'نُشر داخل مستشفيات وشبكات متعدّدة. IHE/HL7.' },
             stats: [ { v: 'IHE/HL7',  l: { en: 'Standards aligned', fr: 'Conforme aux normes', ar: 'متوافق' } },
                      { v: 'Single+',  l: { en: 'Hospital or network', fr: 'Hôpital ou réseau', ar: 'منفرد أو شبكة' } },
                      { v: 'Real-time',l: { en: 'Reporting capability', fr: 'Reporting en temps réel', ar: 'تقارير لحظية' } } ] },
    phases: [
      { step: 1, when: { en: 'Weeks 1–4', fr: 'Semaines 1 à 4', ar: 'الأسابيع ١-٤' }, h: { en: 'Discovery', fr: 'Cadrage', ar: 'الاستكشاف' }, p: { en: 'Analyzer inventory, HIS audit.', fr: 'Inventaire des analyseurs, audit du HIS.', ar: 'جرد المحلّلات، تدقيق HIS.' }, deliv: { en: 'Solution design', fr: 'Conception de la solution', ar: 'تصميم الحل' } },
      { step: 2, when: { en: 'Weeks 5–14', fr: 'Semaines 5 à 14', ar: 'الأسابيع ٥-١٤' }, h: { en: 'Build & pilot', fr: 'Construction et pilote', ar: 'البناء والتجربة' }, p: { en: 'Deploy, integrate analyzers, train.', fr: 'Déploiement, intégration des analyseurs, formation.', ar: 'نشر وتكامل وتدريب.' }, deliv: { en: 'Pilot go-live', fr: 'Mise en production du pilote', ar: 'تشغيل التجربة' } },
      { step: 3, when: { en: 'Weeks 15–22', fr: 'Semaines 15 à 22', ar: 'الأسابيع ١٥-٢٢' }, h: { en: 'Rollout', fr: 'Déploiement global', ar: 'التوسعة' }, p: { en: 'Remaining labs, cross-site routing.', fr: 'Laboratoires restants, routage inter-sites.', ar: 'المختبرات المتبقية، توجيه بين المواقع.' }, deliv: { en: 'Production live', fr: 'Production en service', ar: 'الإنتاج' } },
    ],
    performance: { metrics: [
      { v: '~25%',     t: 'down', l: { en: 'Repeat tests', fr: 'Tests redondants', ar: 'الفحوصات المكرّرة' } },
      { v: 'Real-time',t: 'up',   l: { en: 'Surveillance ready', fr: 'Prêt pour la veille', ar: 'جاهز للرصد' } },
      { v: 'QC',       t: 'up',   l: { en: 'Cross-site quality', fr: 'Qualité inter-sites', ar: 'جودة بين المواقع' } },
      { v: 'IHE',      t: 'flat', l: { en: 'Profiles supported', fr: 'Profils pris en charge', ar: 'الملفات المدعومة' } },
    ], bars: [
      { l: { en: 'Analyzer coverage',  fr: 'Couverture des analyseurs', ar: 'تغطية المحلّلات' }, pct: 92 },
      { l: { en: 'HIS integration',    fr: 'Intégration au HIS', ar: 'تكامل HIS' },     pct: 96 },
      { l: { en: 'Public-health hooks',fr: 'Connecteurs santé publique', ar: 'وصلات الصحة' },    pct: 78 },
      { l: { en: 'Mobile clinician',   fr: 'Application clinicien mobile', ar: 'تطبيق الأطباء' }, pct: 84 },
    ] },
  },
  {
    slug: 'xeye', code: 'RB-05', iconKey: 'xeye', color: '#6E8A6F',
    name:    { en: 'X-Eye AI Suite', fr: 'Suite IA X-Eye', ar: 'X-Eye' },
    sub:     { en: 'AI diagnostic assistance', fr: 'Assistance diagnostique par IA', ar: 'مساعدة تشخيصية ذكية' },
    tagline: { en: 'A second pair of eyes — earlier detection of cancers and pneumonia.', fr: 'Une seconde paire d\'yeux — détection plus précoce des cancers et des pneumopathies.', ar: 'زوج ثانٍ من العيون — كشف أبكر للسرطان والالتهاب الرئوي.' },
    badge:   { big: 'AI', lbl: { en: 'In-workflow', fr: 'Intégré au workflow', ar: 'داخل سير العمل' } },
    chips:   [ { tone: 'mint', en: 'Product · 05', fr: 'Produit · 05', ar: 'منتج · ٠٥' }, { tone: 'good', en: 'AI-native', fr: 'IA native', ar: 'ذكاء أصلي' } ],
    overview: { what: { en: 'X-Eye is the radiology AI suite. Second-read flags inside the PACS worklist — no separate viewer.',
                        fr: 'X-Eye est la suite IA dédiée à la radiologie. Indications de seconde lecture directement dans la worklist PACS — sans viewer séparé.',
                        ar: 'مجموعة الذكاء الاصطناعي للأشعة. قراءة ثانية داخل PACS — بلا عارض منفصل.' },
                kpis: [ { v: 'Workflow', l: { en: 'In worklist', fr: 'Dans la worklist', ar: 'داخل قائمة العمل' } },
                        { v: '+17%',     l: { en: 'Early-detection lift', fr: 'Gain de détection précoce', ar: 'تحسّن الكشف المبكر' } },
                        { v: 'Multi',    l: { en: 'Mammo · Toraks · RibOut', fr: 'Sein · Thorax · Côtes', ar: 'الثدي · الصدر · الأضلاع' } } ] },
    audience: { list: [
      { h: { en: 'High-volume hospitals',fr: 'Hôpitaux à forte volumétrie', ar: 'أحجام تصوير عالية' }, p: { en: 'Thousands of studies per month.', fr: 'Des milliers d\'examens par mois.', ar: 'آلاف الدراسات شهريًا.' } },
      { h: { en: 'Multi-site networks',  fr: 'Réseaux multi-sites', ar: 'شبكات متعددة' }, p: { en: 'Consistent reporting quality.', fr: 'Qualité de compte-rendu homogène.', ar: 'جودة تقارير موحّدة.' } },
      { h: { en: 'Screening programs',   fr: 'Programmes de dépistage', ar: 'برامج مسح' }, p: { en: 'Cancer, TB — scalable AI triage.', fr: 'Cancer, tuberculose — triage IA à grande échelle.', ar: 'سرطان وسل — فرز ذكي.' } },
      { h: { en: 'Tele-rad operators',   fr: 'Opérateurs de télé-radiologie', ar: 'الأشعة عن بُعد' }, p: { en: 'Second-read in centralized reading.', fr: 'Seconde lecture en interprétation centralisée.', ar: 'قراءة ثانية مركزية.' } },
    ] },
    features: { list: [
      { h: { en: 'Inside the worklist', fr: 'Au cœur de la worklist', ar: 'داخل قائمة العمل' }, p: { en: 'Findings next to the study — not a separate app.', fr: 'Les résultats apparaissent à côté de l\'examen, pas dans une application à part.', ar: 'النتائج بجانب الدراسة لا في تطبيق منفصل.' },
        sub: [ { en: 'PACS-native', fr: 'Natif PACS', ar: 'أصلي مع PACS' }, { en: 'Structured overlay', fr: 'Surcouche structurée', ar: 'نتائج مهيكلة' }, { en: '1-click report insertion', fr: 'Insertion au compte-rendu en un clic', ar: 'إدراج التقرير بنقرة' } ] },
      { h: { en: 'Screening-ready modules', fr: 'Modules prêts pour le dépistage', ar: 'وحدات جاهزة للمسح' }, p: { en: 'Mammo, chest, rib — hospital or population scale.', fr: 'Sein, thorax, côtes — échelle hospitalière ou populationnelle.', ar: 'الثدي والصدر والأضلاع — مستشفى أو مسح سكاني.' },
        sub: [ { en: 'Mammo AI', fr: 'IA mammographie', ar: 'ذكاء الثدي' }, { en: 'Chest AI', fr: 'IA thorax', ar: 'ذكاء الصدر' }, { en: 'RibOut',  fr: 'RibOut', ar: 'الأضلاع' } ] },
      { h: { en: 'Single-site or networked', fr: 'Mono-site ou en réseau', ar: 'منفرد أو شبكي' }, p: { en: 'One hospital PACS or centralized archive.', fr: 'PACS d\'un hôpital unique ou archive centralisée.', ar: 'PACS مستشفى واحد أو أرشيف مركزي.' },
        sub: [ { en: 'Retrospective batch', fr: 'Analyse rétrospective par lots', ar: 'تحليل تراجعي' }, { en: 'Prospective reading', fr: 'Lecture prospective', ar: 'قراءة مستقبلية' }, { en: 'Audit logs per module', fr: 'Journaux d\'audit par module', ar: 'سجلات لكل وحدة' } ] },
    ] },
    proof: { summary: { en: 'X-Eye modules are in clinical use. Module-level validation reports during the AI Readiness Assessment.', fr: 'Les modules X-Eye sont utilisés en routine clinique. Rapports de validation par module fournis lors de l\'évaluation de maturité IA.', ar: 'وحدات X-Eye قيد الاستخدام السريري. تقارير تحقّق ضمن تقييم الجاهزية.' },
             stats: [ { v: '+17%', l: { en: 'Early-stage cancer lift', fr: 'Gain sur cancers précoces', ar: 'تحسّن الكشف' } },
                      { v: 'Multi',l: { en: 'Modules', fr: 'Modules', ar: 'الوحدات' } },
                      { v: 'PACS', l: { en: 'Our + third-party', fr: 'Le nôtre et tiers', ar: 'لنا وغيرنا' } } ] },
    phases: [
      { step: 1, when: { en: 'Weeks 1–3', fr: 'Semaines 1 à 3', ar: 'الأسابيع ١-٣' }, h: { en: 'Discovery & fit', fr: 'Cadrage et adéquation', ar: 'الاستكشاف والمطابقة' }, p: { en: 'Imaging audit, module selection.', fr: 'Audit de l\'imagerie, sélection des modules.', ar: 'تدقيق التصوير، اختيار الوحدات.' }, deliv: { en: 'Fit report', fr: 'Rapport d\'adéquation', ar: 'تقرير الملاءمة' } },
      { step: 2, when: { en: 'Weeks 4–10', fr: 'Semaines 4 à 10', ar: 'الأسابيع ٤-١٠' }, h: { en: 'Build & pilot', fr: 'Construction et pilote', ar: 'البناء والتجربة' }, p: { en: 'Worklist integration, pilot.', fr: 'Intégration à la worklist, pilote.', ar: 'تكامل وتجربة.' }, deliv: { en: 'Pilot go-live', fr: 'Mise en production du pilote', ar: 'تشغيل التجربة' } },
      { step: 3, when: { en: 'Weeks 11–18', fr: 'Semaines 11 à 18', ar: 'الأسابيع ١١-١٨' }, h: { en: 'Rollout & monitoring', fr: 'Déploiement et supervision', ar: 'التوسعة والرصد' }, p: { en: 'Rollout across sites, quality monitoring.', fr: 'Déploiement sur tous les sites, suivi qualité.', ar: 'توسعة ورصد جودة.' }, deliv: { en: 'Production live', fr: 'Production en service', ar: 'الإنتاج' } },
    ],
    performance: { metrics: [
      { v: '+17%', t: 'up',   l: { en: 'Early-stage cancer detection', fr: 'Détection des cancers précoces', ar: 'كشف السرطان المبكر' } },
      { v: '~92%', t: 'up',   l: { en: 'Module specificity (avg)', fr: 'Spécificité moyenne des modules', ar: 'دقة الوحدات' } },
      { v: '<10s', t: 'down', l: { en: 'Inference / study', fr: 'Inférence par examen', ar: 'زمن التحليل' } },
      { v: 'Audit',t: 'flat', l: { en: 'Per-finding audit trail', fr: 'Piste d\'audit par résultat', ar: 'مسار تدقيق لكل نتيجة' } },
    ], bars: [
      { l: { en: 'Mammo module',        fr: 'Module mammographie', ar: 'وحدة الثدي' },  pct: 91 },
      { l: { en: 'Chest module',        fr: 'Module thorax', ar: 'وحدة الصدر' },  pct: 88 },
      { l: { en: 'Worklist integration',fr: 'Intégration à la worklist', ar: 'عمق التكامل' }, pct: 95 },
      { l: { en: 'Template adoption',   fr: 'Adoption des modèles', ar: 'تبنّي القوالب' }, pct: 80 },
    ] },
  },
  {
    slug: 'teleradiology', code: 'RB-06', iconKey: 'tele', color: '#4D8085',
    name:    { en: 'Tele-radiology', fr: 'Télé-radiologie', ar: 'الأشعة عن بُعد' },
    sub:     { en: 'Cross-facility reading at regional scale', fr: 'Interprétation inter-établissements à l\'échelle régionale', ar: 'قراءة بين المنشآت على نطاق إقليمي' },
    tagline: { en: 'Connect any PACS — including third-party — to specialist radiologists.', fr: 'Connecte n\'importe quel PACS — y compris tiers — à des radiologues spécialisés.', ar: 'اربط أي PACS بأخصائيي الأشعة.' },
    badge:   { big: '300+', lbl: { en: 'Hospitals on national network', fr: 'Hôpitaux sur le réseau national', ar: 'مستشفى على شبكة وطنية' } },
    chips:   [ { tone: 'mint', en: 'Product · 06', fr: 'Produit · 06', ar: 'منتج · ٠٦' }, { tone: 'good', en: 'PACS-agnostic', fr: 'Indépendant du PACS', ar: 'محايد PACS' } ],
    overview: { what: { en: 'Tele-radiology sits above hospital PACS. Connects studies from many sites — even third-party PACS — into specialist reading worklists.',
                        fr: 'La télé-radiologie s\'appuie sur les PACS hospitaliers. Elle rassemble les examens de nombreux sites — y compris des PACS tiers — dans des worklists pour radiologues spécialisés.',
                        ar: 'تقع فوق أنظمة PACS. تربط دراسات من مواقع كثيرة — حتى من خارج المنصّة — بقوائم عمل الأخصائيين.' },
                kpis: [ { v: '300+',    l: { en: 'Hospitals connected ref', fr: 'Référence : hôpitaux connectés', ar: 'مرجع' } },
                        { v: 'Any PACS',l: { en: 'Vendor-neutral', fr: 'Neutre vis-à-vis des éditeurs', ar: 'محايد' } },
                        { v: 'Filmless',l: { en: 'Network-wide', fr: 'Sur tout le réseau', ar: 'عبر الشبكة' } } ] },
    audience: { list: [
      { h: { en: 'National imaging programs', fr: 'Programmes nationaux d\'imagerie', ar: 'برامج وطنية' }, p: { en: 'Regional or national imaging.', fr: 'Imagerie régionale ou nationale.', ar: 'برامج إقليمية أو وطنية.' } },
      { h: { en: 'Hospital chains',           fr: 'Chaînes hospitalières', ar: 'سلاسل مستشفيات' }, p: { en: 'Rural facilities lacking radiologists.', fr: 'Établissements ruraux sans radiologues sur place.', ar: 'منشآت ريفية بدون أخصائيين.' } },
      { h: { en: 'Screening operators',       fr: 'Opérateurs de dépistage', ar: 'مشغّلو المسح' }, p: { en: 'Cancer, TB, population scale.', fr: 'Cancer, tuberculose, à l\'échelle populationnelle.', ar: 'سرطان، سل، مسوحات.' } },
      { h: { en: 'Multi-vendor environments', fr: 'Environnements multi-éditeurs', ar: 'بيئات متعددة الموردين' }, p: { en: 'Sites with third-party PACS.', fr: 'Sites équipés de PACS tiers.', ar: 'مواقع بأنظمة من جهات أخرى.' } },
    ] },
    features: { list: [
      { h: { en: 'PACS-agnostic', fr: 'Indépendant du PACS', ar: 'محايد تجاه PACS' }, p: { en: 'Standard DICOM/HL7 connectors. A layer above PACS, not a replacement.', fr: 'Connecteurs DICOM/HL7 standards. Une couche au-dessus des PACS, sans les remplacer.', ar: 'وصلات معيارية. طبقة فوق PACS لا بديل عنها.' },
        sub: [ { en: 'Standards-based', fr: 'Basé sur les normes', ar: 'معياري' }, { en: 'Vendor-neutral archive', fr: 'Archive indépendante des éditeurs', ar: 'أرشيف محايد' }, { en: 'Cross-vendor governance', fr: 'Gouvernance multi-éditeurs', ar: 'حوكمة بين البائعين' } ] },
      { h: { en: 'Specialist reach without travel', fr: 'Accès aux spécialistes sans déplacement', ar: 'وصول الأخصائيين دون سفر' }, p: { en: 'Rural sites access specialists in major cities.', fr: 'Les sites ruraux accèdent à des spécialistes des grandes villes.', ar: 'المواقع الريفية تصل لأخصائيي المدن.' },
        sub: [ { en: 'Sub-specialty routing', fr: 'Routage par sur-spécialité', ar: 'توجيه التخصّصات' }, { en: 'Load balancing', fr: 'Répartition de charge', ar: 'توازن الحِمل' }, { en: 'Mobile + web', fr: 'Mobile et web', ar: 'جوّال وويب' } ] },
      { h: { en: 'AI-assisted screening', fr: 'Dépistage assisté par IA', ar: 'مسح ذكي' }, p: { en: 'Combined with X-Eye, supports population screening.', fr: 'Couplé à X-Eye, prend en charge le dépistage populationnel.', ar: 'بالتكامل مع X-Eye، يدعم المسح السكاني.' },
        sub: [ { en: 'Triage by AI score', fr: 'Triage par score IA', ar: 'فرز ذكي' }, { en: 'Governance logs', fr: 'Journaux de gouvernance', ar: 'سجلات حوكمة' }, { en: 'Patient consent', fr: 'Consentement patient', ar: 'موافقة المرضى' } ] },
    ] },
    proof: { summary: { en: 'A national tele-radiology program in Kazakhstan connecting hundreds of hospitals into one reading network.', fr: 'Un programme national de télé-radiologie au Kazakhstan reliant des centaines d\'hôpitaux dans un réseau de lecture unique.', ar: 'برنامج وطني للأشعة عن بُعد في كازاخستان يربط مئات المستشفيات.' },
             stats: [ { v: '300+',     l: { en: 'Hospitals on the network', fr: 'Hôpitaux sur le réseau', ar: 'مستشفى على الشبكة' } },
                      { v: 'Filmless', l: { en: 'Across the network', fr: 'Sur tout le réseau', ar: 'عبر الشبكة' } },
                      { v: 'Any PACS', l: { en: 'Our + third-party', fr: 'Le nôtre et tiers', ar: 'لنا وغيرنا' } } ] },
    phases: [
      { step: 1, when: { en: 'Weeks 1–4', fr: 'Semaines 1 à 4', ar: 'الأسابيع ١-٤' }, h: { en: 'Discovery & architecture', fr: 'Cadrage et architecture', ar: 'الاستكشاف والمعمارية' }, p: { en: 'Network design, governance.', fr: 'Conception du réseau, gouvernance.', ar: 'تصميم الشبكة، الحوكمة.' }, deliv: { en: 'Solution design', fr: 'Conception de la solution', ar: 'تصميم الحل' } },
      { step: 2, when: { en: 'Weeks 5–14', fr: 'Semaines 5 à 14', ar: 'الأسابيع ٥-١٤' }, h: { en: 'Central hub & pilot', fr: 'Hub central et pilote', ar: 'المركز والتجربة' }, p: { en: 'Two-site pilot, specialist onboarding.', fr: 'Pilote sur deux sites, intégration des spécialistes.', ar: 'تجربة موقعَين، إدخال الأخصائيين.' }, deliv: { en: 'Pilot go-live', fr: 'Mise en production du pilote', ar: 'تشغيل التجربة' } },
      { step: 3, when: { en: 'Weeks 15–26', fr: 'Semaines 15 à 26', ar: 'الأسابيع ١٥-٢٦' }, h: { en: 'Network onboarding', fr: 'Intégration du réseau', ar: 'إدخال الشبكة' }, p: { en: 'Remaining sites, screening integration.', fr: 'Sites restants, intégration du dépistage.', ar: 'المواقع المتبقية، تكامل المسح.' }, deliv: { en: 'Production live', fr: 'Production en service', ar: 'الإنتاج' } },
    ],
    performance: { metrics: [
      { v: '300+',     t: 'up',   l: { en: 'National network sites', fr: 'Sites du réseau national', ar: 'مواقع على الشبكة' } },
      { v: 'Filmless', t: 'flat', l: { en: 'Network ops', fr: 'Exploitation du réseau', ar: 'عمليات' } },
      { v: '< 30 min', t: 'down', l: { en: 'Specialist turnaround', fr: 'Délai de réponse spécialiste', ar: 'زمن الاستجابة' } },
      { v: 'Any',      t: 'flat', l: { en: 'PACS compatibility', fr: 'Compatibilité PACS', ar: 'توافق PACS' } },
    ], bars: [
      { l: { en: 'PACS connectors',     fr: 'Connecteurs PACS', ar: 'وصلات PACS' },     pct: 90 },
      { l: { en: 'Specialist coverage', fr: 'Couverture spécialistes', ar: 'تغطية الأخصائيين' }, pct: 85 },
      { l: { en: 'Mobile viewer',       fr: 'Viewer mobile', ar: 'العارض على الجوّال' }, pct: 88 },
      { l: { en: 'Screening readiness', fr: 'Préparation au dépistage', ar: 'جاهزية المسح' },     pct: 92 },
    ] },
  },
  {
    slug: 'nefro', code: 'RB-07', iconKey: 'nefro', color: '#5A93A4',
    name:    { en: 'TeleDialysis (Nefro)', fr: 'Télé-dialyse (Nefro)', ar: 'الغسيل عن بُعد (Nefro)' },
    sub:     { en: 'Dialysis management + patient app', fr: 'Gestion de la dialyse + application patient', ar: 'نظام إدارة الغسيل وتطبيق المريض' },
    tagline: { en: 'Helps dialysis patients manage their health from home.', fr: 'Aide les patients dialysés à gérer leur santé depuis chez eux.', ar: 'يساعد مرضى الغسيل على إدارة صحّتهم من المنزل.' },
    badge:   { big: 'App', lbl: { en: 'Patient companion', fr: 'Compagnon patient', ar: 'تطبيق المريض' } },
    chips:   [ { tone: 'mint', en: 'Product · 07', fr: 'Produit · 07', ar: 'منتج · ٠٧' }, { tone: 'info', en: 'Care continuity', fr: 'Continuité des soins', ar: 'استمرارية الرعاية' } ],
    overview: { what: { en: 'Dialysis management system + patient mobile app. Treatment plans, adherence, care-team messaging from home.',
                        fr: 'Système de gestion de la dialyse couplé à une application mobile patient. Plans de traitement, observance, échanges avec l\'équipe soignante depuis le domicile.',
                        ar: 'نظام إدارة الغسيل وتطبيق جوّال للمرضى. خطط العلاج، الالتزام، مراسلة فريق الرعاية.' },
                kpis: [ { v: 'Mobile', l: { en: 'iOS + Android', fr: 'iOS et Android', ar: 'iOS وAndroid' } },
                        { v: 'Care',   l: { en: 'Beyond the chair', fr: 'Au-delà de la séance', ar: 'بعد الجلسة' } },
                        { v: 'EMR',    l: { en: 'Linked to HIS', fr: 'Relié au HIS', ar: 'مرتبط بـ HIS' } } ] },
    audience: { list: [
      { h: { en: 'Dialysis units',       fr: 'Unités de dialyse', ar: 'وحدات الغسيل' }, p: { en: 'Hospital and standalone centers.', fr: 'Centres hospitaliers et indépendants.', ar: 'وحدات بالمستشفيات والمستقلة.' } },
      { h: { en: 'Chronic-care networks',fr: 'Réseaux de soins chroniques', ar: 'شبكات أمراض مزمنة' }, p: { en: 'CKD populations across regions.', fr: 'Populations IRC à l\'échelle régionale.', ar: 'مرضى الكلى المزمن.' } },
      { h: { en: 'Home dialysis',         fr: 'Dialyse à domicile', ar: 'الغسيل المنزلي' }, p: { en: 'Peritoneal or home hemo with monitoring.', fr: 'Péritonéale ou hémodialyse à domicile avec suivi.', ar: 'بريتوني أو منزلي.' } },
      { h: { en: 'MoH initiatives',       fr: 'Initiatives ministérielles', ar: 'مبادرات وزارة الصحة' }, p: { en: 'CKD registries and screening.', fr: 'Registres IRC et dépistage.', ar: 'سجلات الكلى والمسح.' } },
    ] },
    features: { list: [
      { h: { en: 'Dialysis-aware scheduling', fr: 'Planification adaptée à la dialyse', ar: 'جدولة واعية بالغسيل' }, p: { en: 'Multi-shift, multi-chair scheduling.', fr: 'Planification multi-postes et multi-vacations.', ar: 'جدولة بالورديات والكراسي.' },
        sub: [ { en: 'Chair / machine assign', fr: 'Affectation poste / appareil', ar: 'تخصيص الكراسي والأجهزة' }, { en: 'Shift planning', fr: 'Planification des vacations', ar: 'تخطيط الورديات' }, { en: 'Vascular access tracking', fr: 'Suivi de l\'abord vasculaire', ar: 'تتبّع الوصول الوعائي' } ] },
      { h: { en: 'Patient mobile app', fr: 'Application mobile patient', ar: 'تطبيق المريض' }, p: { en: 'Treatment plan, meds, fluid/weight log, care-team messaging.', fr: 'Plan de traitement, médicaments, suivi du poids et des apports hydriques, échanges avec l\'équipe.', ar: 'خطة العلاج، الأدوية، السوائل، المراسلة.' },
        sub: [ { en: 'Daily weight + fluid', fr: 'Poids et hydratation au quotidien', ar: 'الوزن والسوائل اليومي' }, { en: 'Med adherence', fr: 'Observance médicamenteuse', ar: 'الالتزام الدوائي' }, { en: 'Secure messaging', fr: 'Messagerie sécurisée', ar: 'مراسلة آمنة' } ] },
      { h: { en: 'Outcome dashboards', fr: 'Tableaux de bord cliniques', ar: 'لوحات النتائج' }, p: { en: 'Kt/V trends, adherence, hospitalization risk.', fr: 'Tendances Kt/V, observance, risque d\'hospitalisation.', ar: 'اتجاهات Kt/V، الالتزام، خطر التنويم.' },
        sub: [ { en: 'Kt/V trend', fr: 'Évolution du Kt/V', ar: 'اتجاه Kt/V' }, { en: 'Anemia / phosphate', fr: 'Anémie / phosphate', ar: 'فقر الدم والفسفور' }, { en: 'Risk stratification', fr: 'Stratification du risque', ar: 'تصنيف الخطر' } ] },
    ] },
    proof: { summary: { en: 'Part of the broader chronic-care portfolio, integrated with HIS/EMR for unified records.', fr: 'Fait partie d\'un portefeuille plus large dédié aux maladies chroniques, intégré au HIS/DPI pour un dossier unifié.', ar: 'جزء من محفظة الرعاية المزمنة، متكامل مع HIS/EMR.' },
             stats: [ { v: 'HIS', l: { en: 'Integrated record', fr: 'Dossier intégré', ar: 'سجل متكامل' } },
                      { v: 'App', l: { en: 'iOS + Android', fr: 'iOS et Android', ar: 'iOS وAndroid' } },
                      { v: 'Home',l: { en: 'Home dialysis-ready', fr: 'Prêt pour la dialyse à domicile', ar: 'يدعم المنزلي' } } ] },
    phases: [
      { step: 1, when: { en: 'Weeks 1–3', fr: 'Semaines 1 à 3', ar: 'الأسابيع ١-٣' }, h: { en: 'Discovery', fr: 'Cadrage', ar: 'الاستكشاف' }, p: { en: 'Workflow mapping, integration plan.', fr: 'Cartographie des processus, plan d\'intégration.', ar: 'تخطيط سير العمل والتكامل.' }, deliv: { en: 'Solution design', fr: 'Conception de la solution', ar: 'تصميم الحل' } },
      { step: 2, when: { en: 'Weeks 4–10', fr: 'Semaines 4 à 10', ar: 'الأسابيع ٤-١٠' }, h: { en: 'Build & pilot', fr: 'Construction et pilote', ar: 'البناء والتجربة' }, p: { en: 'Deploy, app rollout to cohort.', fr: 'Déploiement, mise à disposition de l\'application à une cohorte.', ar: 'نشر، إطلاق التطبيق لمجموعة.' }, deliv: { en: 'Pilot go-live', fr: 'Mise en production du pilote', ar: 'تشغيل التجربة' } },
      { step: 3, when: { en: 'Weeks 11–18', fr: 'Semaines 11 à 18', ar: 'الأسابيع ١١-١٨' }, h: { en: 'Network rollout', fr: 'Déploiement réseau', ar: 'توسعة الشبكة' }, p: { en: 'Additional centers + home cohort.', fr: 'Centres supplémentaires et cohorte à domicile.', ar: 'مراكز إضافية ومنزلي.' }, deliv: { en: 'Production live', fr: 'Production en service', ar: 'الإنتاج' } },
    ],
    performance: { metrics: [
      { v: 'Kt/V', t: 'up',   l: { en: 'Outcomes tracking', fr: 'Suivi des résultats cliniques', ar: 'تتبّع النتائج' } },
      { v: '~25%', t: 'down', l: { en: 'Missed-session rate', fr: 'Séances manquées', ar: 'الجلسات الفائتة' } },
      { v: 'Daily',t: 'up',   l: { en: 'Fluid / weight log', fr: 'Journal poids / hydratation', ar: 'تسجيل يومي' } },
      { v: 'Home', t: 'up',   l: { en: 'Home-dialysis readiness', fr: 'Prêt pour la dialyse à domicile', ar: 'جاهزية منزلي' } },
    ], bars: [
      { l: { en: 'Patient app adoption', fr: 'Adoption de l\'application patient', ar: 'تبنّي التطبيق' },   pct: 78 },
      { l: { en: 'Med adherence',        fr: 'Observance médicamenteuse', ar: 'الالتزام الدوائي' }, pct: 82 },
      { l: { en: 'HIS integration',      fr: 'Intégration au HIS', ar: 'تكامل HIS' },        pct: 95 },
      { l: { en: 'Home program coverage',fr: 'Couverture du programme domicile', ar: 'البرنامج المنزلي' },  pct: 60 },
    ] },
  },
  {
    slug: 'assessment', code: 'RB-08', iconKey: 'assessment', color: '#566B7A',
    name:    { en: 'Assessment', fr: 'Évaluation', ar: 'التقييم' },
    sub:     { en: 'Free scoping & AI readiness', fr: 'Cadrage gratuit et maturité IA', ar: 'تقييم مجاني للنطاق وجاهزية الذكاء' },
    tagline: { en: 'A two-part scoping exercise — Questionnaire + AI Analysis — that turns your hospital reality into a sized, phased proposal.',
               fr: 'Un cadrage en deux volets — questionnaire et analyse IA — qui transforme la réalité de votre hôpital en une proposition dimensionnée et phasée.',
               ar: 'تقييم من جزئين — استبيان + تحليل ذكاء.' },
    badge:   { big: 'Free', lbl: { en: 'For qualified prospects', fr: 'Pour les prospects qualifiés', ar: 'للجهات المؤهّلة' } },
    chips:   [ { tone: 'mint', en: 'Service · 01', fr: 'Service · 01', ar: 'خدمة · ٠١' }, { tone: 'good', en: 'No commitment', fr: 'Sans engagement', ar: 'دون التزام' } ],
    overview: { what: { en: 'Before any product proposal we run a structured assessment. Part 1: Questionnaire (HIS, LIS, PACS, ICUMS, dialysis). Part 2: AI Analysis (modality inventory + reading capacity).',
                        fr: 'Avant toute proposition commerciale, nous menons une évaluation structurée. Volet 1 : questionnaire (HIS, LIS, PACS, ICUMS, dialyse). Volet 2 : analyse IA (inventaire des modalités et capacité de lecture).',
                        ar: 'قبل أي عرض، نُجري تقييمًا. الجزء ١: استبيان (HIS، LIS، PACS، ICUMS، غسيل). الجزء ٢: تحليل الذكاء (الأجهزة وقدرة القراءة).' },
                kpis: [ { v: '2 parts', l: { en: 'Questionnaire + AI', fr: 'Questionnaire + IA', ar: 'استبيان + ذكاء' } },
                        { v: '2–3 wks',  l: { en: 'Turnaround', fr: 'Délai de livraison', ar: 'مدة الإنجاز' } },
                        { v: 'Free',     l: { en: 'For first 5 strategic', fr: 'Pour les 5 premiers comptes stratégiques', ar: 'لأوّل ٥ جهات' } } ] },
    audience: { list: [
      { h: { en: 'New deployments',     fr: 'Nouveaux déploiements', ar: 'عمليات نشر جديدة' }, p: { en: 'Selecting first HIS / PACS / LIS.', fr: 'Choix d\'un premier HIS / PACS / LIS.', ar: 'اختيار أول نظام.' } },
      { h: { en: 'Replacements',        fr: 'Remplacements', ar: 'استبدال' }, p: { en: 'Replacing legacy or fragmented stacks.', fr: 'Remplacement de systèmes anciens ou fragmentés.', ar: 'استبدال أنظمة قديمة أو مشتّتة.' } },
      { h: { en: 'Multi-site networks', fr: 'Réseaux multi-sites', ar: 'شبكات متعددة' }, p: { en: 'Scoping regional rollout.', fr: 'Cadrage d\'un déploiement régional.', ar: 'نشر إقليمي.' } },
      { h: { en: 'AI / imaging programs',fr: 'Programmes IA et imagerie', ar: 'برامج الذكاء والأشعة' }, p: { en: 'Sizing AI vs modality mix.', fr: 'Dimensionnement IA selon le parc de modalités.', ar: 'تحديد الذكاء حسب الأجهزة.' } },
    ] },
    features: { list: [
      { h: { en: 'Part 1 — Module Questionnaire', fr: 'Volet 1 — Questionnaire par module', ar: 'الجزء ١ — استبيان الوحدات' },
        p: { en: 'Structured form per module: HIS (17q), LIS (8q), PACS (7q), ICUMS (9q), Hemodialysis (10q).', fr: 'Formulaire structuré par module : HIS (17 q), LIS (8 q), PACS (7 q), ICUMS (9 q), hémodialyse (10 q).', ar: 'استبيان لكل وحدة.' },
        sub: [ { en: 'HIS: beds, departments, users, OPD', fr: 'HIS : lits, services, utilisateurs, externe', ar: 'HIS: الأسرّة، الأقسام، المستخدمون، العيادات' },
               { en: 'LIS: tests/day, analyzers',          fr: 'LIS : tests/jour, analyseurs', ar: 'LIS: الفحوصات، المحلّلات' },
               { en: 'PACS: radiology team, inventory',    fr: 'PACS : équipe radio, inventaire', ar: 'PACS: الفريق، الجرد' } ] },
      { h: { en: 'Part 2 — AI Analysis', fr: 'Volet 2 — Analyse IA', ar: 'الجزء ٢ — تحليل الذكاء' },
        p: { en: 'Modality-level inventory: hospital, room, modality, brand, faulty status, daily/yearly volumes.', fr: 'Inventaire par modalité : hôpital, salle, modalité, marque, état, volumes quotidiens et annuels.', ar: 'جرد على مستوى الأجهزة.' },
        sub: [ { en: 'CT · MRI · X-Ray · Mammo', fr: 'Scanner · IRM · Radio · Mammo', ar: 'مقطعية · رنين · سينية · ثدي' },
               { en: 'Faulty / analogue tracking', fr: 'Suivi pannes / analogique', ar: 'العطل والتناظري' },
               { en: 'Reading capacity per site', fr: 'Capacité de lecture par site', ar: 'قدرة القراءة' } ] },
      { h: { en: 'Output — sized proposal', fr: 'Livrable — proposition dimensionnée', ar: 'المخرج — عرض مرحلي' },
        p: { en: 'Scorecard + sizing + phased rollout, usually within a week.', fr: 'Scorecard, dimensionnement et déploiement phasé, généralement sous une semaine.', ar: 'بطاقة تقييم + حجم + عرض مرحلي خلال أسبوع.' },
        sub: [ { en: 'AI Readiness scorecard', fr: 'Scorecard de maturité IA', ar: 'بطاقة جاهزية الذكاء' },
               { en: 'Module-level sizing', fr: 'Dimensionnement par module', ar: 'حجم على مستوى الوحدة' },
               { en: 'Phase 1 proof-of-value', fr: 'Phase 1 : preuve de valeur', ar: 'إثبات القيمة' } ] },
    ] },
    proof: { summary: { en: 'We run this assessment with every serious prospect. Free for the first five strategic prospects per quarter.',
                        fr: 'Nous menons cette évaluation avec chaque prospect sérieux. Gratuit pour les cinq premiers comptes stratégiques par trimestre.',
                        ar: 'نُجري هذا التقييم مع كل جهة جادّة. مجاني لأول خمس جهات لكل ربع.' },
             stats: [ { v: '~3 wk', l: { en: 'On-site + analysis', fr: 'Terrain et analyse', ar: 'ميداني وتحليلي' } },
                      { v: '1 wk',  l: { en: 'Proposal after inputs', fr: 'Proposition après réception des données', ar: 'العرض بعد المدخلات' } },
                      { v: '5 / Q', l: { en: 'Free slots / quarter', fr: 'Places gratuites par trimestre', ar: 'مقاعد مجانية لكل ربع' } } ] },
    phases: [
      { step: 1, when: { en: 'Week 1', fr: 'Semaine 1', ar: 'الأسبوع ١' }, h: { en: 'Discovery & kickoff', fr: 'Cadrage et lancement', ar: 'الاستكشاف والانطلاق' }, p: { en: '30-min call, NDAs, templates sent.', fr: 'Appel de 30 min, NDA, envoi des modèles.', ar: 'مكالمة، اتفاقيات سرية، نماذج.' }, deliv: { en: 'Filled templates', fr: 'Modèles complétés', ar: 'نماذج مكتملة' } },
      { step: 2, when: { en: 'Weeks 2–3', fr: 'Semaines 2 à 3', ar: 'الأسابيع ٢-٣' }, h: { en: 'Inventory + interviews', fr: 'Inventaire et entretiens', ar: 'الجرد والمقابلات' }, p: { en: 'Verify inventory, short interviews.', fr: 'Vérification de l\'inventaire, entretiens ciblés.', ar: 'تحقّق من الجرد، مقابلات.' }, deliv: { en: 'Verified inventory', fr: 'Inventaire vérifié', ar: 'جرد متحقّق' } },
      { step: 3, when: { en: 'Week 4', fr: 'Semaine 4', ar: 'الأسبوع ٤' }, h: { en: 'Scorecard & proposal', fr: 'Scorecard et proposition', ar: 'البطاقة والعرض' }, p: { en: 'Readiness scorecard, sizing, phased proposal.', fr: 'Scorecard de maturité, dimensionnement, proposition phasée.', ar: 'بطاقة تقييم، حجم، عرض مرحلي.' }, deliv: { en: 'Scorecard + proposal', fr: 'Scorecard et proposition', ar: 'بطاقة + عرض' } },
    ],
    performance: { metrics: [
      { v: '4 wk',  t: 'flat', l: { en: 'Assessment cycle', fr: 'Cycle d\'évaluation', ar: 'دورة التقييم' } },
      { v: '5',     t: 'up',   l: { en: 'Modules covered', fr: 'Modules couverts', ar: 'الوحدات' } },
      { v: '60min', t: 'flat', l: { en: 'Readout session', fr: 'Session de restitution', ar: 'جلسة العرض' } },
      { v: '0 SAR', t: 'down', l: { en: 'Cost (qualified)', fr: 'Coût (prospects qualifiés)', ar: 'التكلفة (مؤهّلون)' } },
    ], bars: [
      { l: { en: 'Questionnaire coverage', fr: 'Couverture du questionnaire', ar: 'تغطية الاستبيان' },  pct: 100 },
      { l: { en: 'AI / imaging analysis',  fr: 'Analyse IA et imagerie', ar: 'تحليل الذكاء' },     pct: 100 },
      { l: { en: 'Integration mapping',    fr: 'Cartographie des intégrations', ar: 'تخطيط التكامل' },    pct: 90 },
      { l: { en: 'Sizing model accuracy',  fr: 'Précision du modèle de dimensionnement', ar: 'دقة نموذج الحجم' },   pct: 92 },
    ] },
  },
  {
    slug: 'contact', code: 'RB-09', iconKey: 'contact', color: '#73917A',
    isLink:  true, href: 'contact.html',
    name:    { en: 'Contact', fr: 'Contact', ar: 'تواصل' },
    sub:     { en: 'Talk to us', fr: 'Parlons-en', ar: 'تحدث إلينا' },
  },
];

window.RIBAL_ICONS = {
  his:  `<svg viewBox="0 0 48 48" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M8 41h32"/><path d="M12 41V15l12-7 12 7v26"/><path d="M24 19v9M19.5 23.5h9"/><path d="M19 41v-8h10v8"/></svg>`,
  pacs: `<svg viewBox="0 0 48 48" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="7" y="11" width="34" height="26" rx="3"/><circle cx="33" cy="19" r="2.4"/><path d="M11 31l7-7 5 5 4-4 10 10"/><path d="M11 19h6M11 25h4"/></svg>`,
  icu:  `<svg viewBox="0 0 48 48" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M6 24h6l3-7 6 14 4-9 3 5h14"/><circle cx="38" cy="32" r="2"/></svg>`,
  lis:  `<svg viewBox="0 0 48 48" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M17 6h14"/><path d="M19 6v28a5 5 0 0 0 10 0V6"/><path d="M19 22c2 1 4 1 5 0s3-1 5 0"/><path d="M19 30c2 1 4 1 5 0s3-1 5 0"/></svg>`,
  xeye: `<svg viewBox="0 0 48 48" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M4 24s7-12 20-12 20 12 20 12-7 12-20 12S4 24 4 24z"/><circle cx="24" cy="24" r="5"/><path d="M37 7l1.4 3.2L42 11.5l-3.6 1.4L37 16l-1.4-3.1L32 11.5l3.6-1.3z"/></svg>`,
  tele: `<svg viewBox="0 0 48 48" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M4 19a28 28 0 0 1 40 0"/><path d="M10 25a20 20 0 0 1 28 0"/><path d="M16 31a12 12 0 0 1 16 0"/><circle cx="24" cy="39" r="2.3"/></svg>`,
  nefro:`<svg viewBox="0 0 48 48" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M24 5c-3 5-13 14-13 23a13 13 0 0 0 26 0c0-9-10-18-13-23z"/><path d="M17.5 28a6.5 6.5 0 0 0 6.5 6.5"/></svg>`,
  assessment:`<svg viewBox="0 0 48 48" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="11" y="8" width="26" height="34" rx="3"/><rect x="18" y="5" width="12" height="6" rx="2" fill="currentColor" stroke="none"/><path d="M16 20l3 3 6-6"/><line x1="27" y1="20" x2="33" y2="20"/><path d="M16 30l3 3 6-6"/><line x1="27" y1="30" x2="33" y2="30"/></svg>`,
  contact:`<svg viewBox="0 0 48 48" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M40 33v6a3 3 0 0 1-3.3 3 30 30 0 0 1-13-4.7 30 30 0 0 1-9-9A30 30 0 0 1 10 15.3 3 3 0 0 1 13 12h6a3 3 0 0 1 3 2.6c.2 1.3.5 2.6 1 3.9a3 3 0 0 1-.7 3.2L20 24.3a24 24 0 0 0 9 9l2.6-2.6a3 3 0 0 1 3.2-.7c1.3.5 2.6.8 3.9 1A3 3 0 0 1 40 33z"/></svg>`,
};
